version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: apt-get update
      - run: sudo apt-get install -y gcc g++ cmake clang-format-8 cppcheck

workflows:
  build-and-test:
    jobs:
      - build-and-test
